In [1]:
#data encoding>> converting categorical columns into numeric
#Nominal/OHE
#label and ordinal encoding
#Target guided ordinal encoding

In [2]:
#Nominal/OHE >> binary vector for each categories
#example : single, married, separated
#single :[1, 0, 0]
#married: [0, 1, 0]
#separated: [0, 0, 1]

In [3]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [4]:
df = pd.DataFrame({'status': ['single', 'married', 'separated', 'single', 'single', 'married', 'married']})

In [5]:
df

status
0     single
1    married
2  separated
3     single
4     single
5    married
6    married

In [6]:
encoder = OneHotEncoder()

In [7]:
encoder

OneHotEncoder()

In [8]:
encoded = encoder.fit_transform(df[['status']]).toarray()

In [9]:
encoder.get_feature_names_out()

array(['status_married', 'status_separated', 'status_single'],
      dtype=object)

In [10]:
encoder_df = pd.DataFrame(encoded, columns = encoder.get_feature_names_out())

In [11]:
encoder_df

status_married  status_separated  status_single
0             0.0               0.0            1.0
1             1.0               0.0            0.0
2             0.0               1.0            0.0
3             0.0               0.0            1.0
4             0.0               0.0            1.0
5             1.0               0.0            0.0
6             1.0               0.0            0.0

In [12]:
#new data
encoder.transform([['single']]).toarray()

/opt/conda/lib/python3.10/site-packages/sklearn/base.py:409: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 1.]])

In [16]:
pd.concat([df, encoder_df], axis=1)

status  status_married  status_separated  status_single
0     single             0.0               0.0            1.0
1    married             1.0               0.0            0.0
2  separated             0.0               1.0            0.0
3     single             0.0               0.0            1.0
4     single             0.0               0.0            1.0
5    married             1.0               0.0            0.0
6    married             1.0               0.0            0.0

In [17]:
#pd.get_dummies()

In [18]:
import seaborn as sns
sns.load_dataset('tips')

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
#label encoding>> assigns unique label to the categories

In [19]:
df

status
0     single
1    married
2  separated
3     single
4     single
5    married
6    married

In [20]:
from sklearn.preprocessing import LabelEncoder

In [22]:
label_encoder = LabelEncoder()

In [23]:
label_encoder.fit_transform(df[['status']])

/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 1, 2, 2, 0, 0])

In [24]:
label_encoder.transform([['single']])

/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([2])

In [25]:
label_encoder.transform([['separated']])

array([1])

In [26]:
#ordinal encoding

#High school: 1
#graduate: 2
#pg:3
#phd:4

In [27]:
from sklearn.preprocessing import OrdinalEncoder

In [31]:
df = pd.DataFrame({"qualification": ["HS", "GR", "PG", "PhD", "HS", "HS", "PhD","PG" ]})

In [32]:
df

qualification
0            HS
1            GR
2            PG
3           PhD
4            HS
5            HS
6           PhD
7            PG

In [33]:
encoder = OrdinalEncoder(categories=[["HS", "GR", "PG", "PhD"]])

In [35]:
encoder.fit_transform(df[['qualification']])

array([[0.],
       [1.],
       [2.],
       [3.],
       [0.],
       [0.],
       [3.],
       [2.]])

In [37]:
#new data
encoder.transform([['PG']])

/opt/conda/lib/python3.10/site-packages/sklearn/base.py:409: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[2.]])

In [38]:
#Target guided ordinal encoding
#relationship with target variable
# A  lot of unique categories
#Replace the category with the mean and median of respective group target

In [42]:
df = pd.DataFrame({'time':['lunch', 'breakfast', 'dinner', 'lunch', 'breakfast', 'dinner', 'lunch', 'breakfast', 'dinner'],
             'total_bill': [120, 130, 90, 125, 150, 190, 160, 180, 189]})

In [43]:
df

time  total_bill
0      lunch         120
1  breakfast         130
2     dinner          90
3      lunch         125
4  breakfast         150
5     dinner         190
6      lunch         160
7  breakfast         180
8     dinner         189

In [45]:
mean_price = df.groupby('time')['total_bill'].mean().to_dict()

In [46]:
mean_price

{'breakfast': 153.33333333333334, 'dinner': 156.33333333333334, 'lunch': 135.0}

In [47]:
df['time_encoded'] = df['time'].map(mean_price)

In [48]:
df

time  total_bill  time_encoded
0      lunch         120    135.000000
1  breakfast         130    153.333333
2     dinner          90    156.333333
3      lunch         125    135.000000
4  breakfast         150    153.333333
5     dinner         190    156.333333
6      lunch         160    135.000000
7  breakfast         180    153.333333
8     dinner         189    156.333333

In [49]:
sns.load_dataset('tips')

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]