In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


import warnings 
warnings.filterwarnings('ignore')

In [2]:
from sklearn.datasets import make_classification

X, y = make_classification(n_samples=1000, n_features=3, n_redundant=0, n_classes=2, random_state=1)

In [3]:
X.shape

(1000, 3)

In [4]:
X

array([[ 0.60500791,  0.51340375, -1.55859419],
       [ 0.81846819, -1.88473945,  1.49992516],
       [ 0.53437474, -0.01420736,  0.2771265 ],
       ...,
       [ 2.28830983,  3.74857955, -0.5886461 ],
       [-0.28103796, -1.84729902,  1.13548397],
       [ 0.76642645, -1.29293146,  0.88279907]])

In [5]:
y

array([1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=1)

In [7]:
X_train.shape, X_test.shape

((700, 3), (300, 3))

In [8]:
#model training
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier()

In [9]:
clf

KNeighborsClassifier()

In [10]:
clf.fit(X_train, y_train)

KNeighborsClassifier()

In [11]:
y_pred = clf.predict(X_test)

In [12]:
y_pred

array([1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1])

In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [14]:
print(confusion_matrix(y_test, y_pred))

[[122  23]
 [ 21 134]]


In [15]:
print(accuracy_score(y_test, y_pred))

0.8533333333333334


In [16]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.84      0.85       145
           1       0.85      0.86      0.86       155

    accuracy                           0.85       300
   macro avg       0.85      0.85      0.85       300
weighted avg       0.85      0.85      0.85       300



In [18]:
#hyperparameter tuning
from sklearn.model_selection import GridSearchCV

In [19]:
param_grid = {
    'n_neighbors': [3, 5, 6, 7, 9, 11, 13],
    'weights': ['uniform', 'distance'],
    'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
    'leaf_size': [20, 30, 40, 50]
}

In [20]:
grid = GridSearchCV(estimator = clf, param_grid=param_grid, cv = 5, verbose=3)

In [21]:
grid

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'leaf_size': [20, 30, 40, 50],
                         'n_neighbors': [3, 5, 6, 7, 9, 11, 13],
                         'weights': ['uniform', 'distance']},
             verbose=3)

In [22]:
grid.fit(X_train, y_train)

Fitting 5 folds for each of 224 candidates, totalling 1120 fits
[CV 1/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=uniform;, score=0.871 total time=   0.0s
[CV 2/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=uniform;, score=0.850 total time=   0.0s
[CV 3/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=uniform;, score=0.814 total time=   0.0s
[CV 4/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=uniform;, score=0.814 total time=   0.0s
[CV 5/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=uniform;, score=0.793 total time=   0.0s
[CV 1/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=distance;, score=0.857 total time=   0.0s
[CV 2/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=distance;, score=0.836 total time=   0.0s
[CV 3/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=distance;, score=0.807 total time=   0.0s
[CV 4/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=distance;, 

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'leaf_size': [20, 30, 40, 50],
                         'n_neighbors': [3, 5, 6, 7, 9, 11, 13],
                         'weights': ['uniform', 'distance']},
             verbose=3)

In [23]:
grid.best_params_

{'algorithm': 'auto', 'leaf_size': 20, 'n_neighbors': 11, 'weights': 'uniform'}

In [24]:
grid.best_score_

0.8514285714285714

In [26]:
# Predict with the best estimator
best_model = grid.best_estimator_
y_pred_tuned = best_model.predict(X_test)

# Evaluate the tuned model
print("Tuned model performance:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_tuned)}")
print("Classification Report:")
print(classification_report(y_test, y_pred_tuned))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_tuned))

Tuned model performance:
Accuracy: 0.8666666666666667
Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.86      0.86       145
           1       0.87      0.88      0.87       155

    accuracy                           0.87       300
   macro avg       0.87      0.87      0.87       300
weighted avg       0.87      0.87      0.87       300

Confusion Matrix:
[[124  21]
 [ 19 136]]
