In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


import warnings 
warnings.filterwarnings('ignore')

In [2]:
from sklearn.datasets import make_regression
X, y = make_regression(n_samples=1000, n_features=2, noise=3, random_state=1)

In [3]:
X

array([[-0.91542437, -1.94504696],
       [-2.30490794, -0.59246129],
       [-0.43750898, -0.78191168],
       ...,
       [-0.46867382,  0.02186284],
       [-0.44265541,  0.55753264],
       [-0.13971173,  0.85328219]])

In [4]:
y

array([-190.03258306,  -85.26051217,  -79.38260295,  -68.46860406,
          7.6776908 ,  -40.35627711,   37.76165512,  -98.68667297,
       -103.49936616, -111.4844082 ,   74.447244  ,   16.74943836,
       -113.89842347,  127.60069439, -104.93211336,   46.33988172,
         14.22936786,  -67.02417655, -110.81141065, -148.68676949,
          8.82971657,   15.87695178,  -14.63414628,   72.69620209,
        108.28395145,    4.7681583 ,  122.70577279,   26.80503947,
         26.05435416,  -22.0578647 ,   76.52458928, -259.93124079,
         26.45161346,  -43.02760158,   31.73017335,  -41.68557901,
         20.2425586 ,  -38.08420722,  -27.93409336,   94.98962026,
         52.38050255,   94.41735191,   27.21304024,  -40.32774788,
        -42.33719649,   29.52470825,  -25.7761902 ,    8.21058588,
        -64.76327716,  103.57997725,  -95.22499841,  110.24508447,
         30.56383975,   34.43757618, -127.51124629,   73.49122997,
        -29.80642858,  -57.0612244 ,   34.83454862, -174.39757

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=1)

In [6]:
from sklearn.neighbors import KNeighborsRegressor
reg = KNeighborsRegressor()

In [7]:
reg

KNeighborsRegressor()

In [8]:
reg.fit(X_train, y_train)

KNeighborsRegressor()

In [9]:
y_pred = reg.predict(X_test)

In [10]:
y_pred

array([ -31.27303942,  -88.14468143,  168.85297226,   22.12939785,
         80.27311394,   20.83384703,  -19.51050133,  156.86509311,
       -159.67902716,  109.91042019,   64.70847727,   24.20010719,
        -76.62806594,  102.64061341,   24.1667387 , -144.06636376,
        159.05068046,   37.60732392,  -15.31142591,  -11.41367664,
       -164.93285599,   15.05024527,   22.53173543,   36.05628259,
         33.28398704,   20.08907639,  -82.17930555,  -86.87411828,
        147.90956025,  204.87861218,  193.1519867 ,   32.02173891,
         99.94951543,   34.02619759,   69.08547936,   30.81498965,
        -80.92377831,  105.63786574, -178.03626419,  -19.07953517,
        146.46089555,  131.52754938,  -43.00693924, -201.06575474,
        -40.26849982,   10.16533245,  -58.218269  ,   93.23650932,
        -54.09413803,  -46.18563326,   50.62859043,   39.3920481 ,
          8.95089607,  -39.18181838,   -3.12276664,   -6.36871729,
        132.99010398,   57.81542445,  -91.27564861,  131.94178

In [11]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9900695068947865

In [12]:
from sklearn.model_selection import GridSearchCV
param_grid = {
    'n_neighbors': [3, 5, 6, 7, 9, 11, 13],
    'weights': ['uniform', 'distance'],
    'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
    'leaf_size': [20, 30, 40, 50]
}

In [13]:
grid = GridSearchCV(estimator=reg, param_grid=param_grid, cv = 5, verbose = 3)

In [14]:
grid

GridSearchCV(cv=5, estimator=KNeighborsRegressor(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'leaf_size': [20, 30, 40, 50],
                         'n_neighbors': [3, 5, 6, 7, 9, 11, 13],
                         'weights': ['uniform', 'distance']},
             verbose=3)

In [15]:
grid.fit(X_train, y_train)

Fitting 5 folds for each of 224 candidates, totalling 1120 fits
[CV 1/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=uniform;, score=0.991 total time=   0.0s
[CV 2/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=uniform;, score=0.994 total time=   0.0s
[CV 3/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=uniform;, score=0.990 total time=   0.0s
[CV 4/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=uniform;, score=0.987 total time=   0.0s
[CV 5/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=uniform;, score=0.989 total time=   0.0s
[CV 1/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=distance;, score=0.993 total time=   0.0s
[CV 2/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=distance;, score=0.995 total time=   0.0s
[CV 3/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=distance;, score=0.992 total time=   0.0s
[CV 4/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=distance;, 

GridSearchCV(cv=5, estimator=KNeighborsRegressor(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'leaf_size': [20, 30, 40, 50],
                         'n_neighbors': [3, 5, 6, 7, 9, 11, 13],
                         'weights': ['uniform', 'distance']},
             verbose=3)

In [16]:
grid.best_params_

{'algorithm': 'brute',
 'leaf_size': 20,
 'n_neighbors': 3,
 'weights': 'distance'}

In [17]:
grid.best_score_

0.992510275176531

In [18]:
best_model = grid.best_params_

In [ ]:
best_model.predice(