In [1]:
import numpy as np

In [2]:
a = np.zeros(5) #Return a new array of given shape and type, filled with zeros.

In [3]:
a

array([0., 0., 0., 0., 0.])

In [4]:
a.ndim

1

In [5]:
b = np.zeros((3, 4))

In [6]:
b.ndim

2

In [7]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.twos(5) #doesnt exist in numpy

AttributeError: module 'numpy' has no attribute 'twos'

In [9]:
np.array([[2, 2, 2], [2, 2, 2]])

array([[2, 2, 2],
       [2, 2, 2]])

In [10]:
arr = np.zeros((3, 4))

In [11]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
arr.ndim

2

In [13]:
#3 dimensional array
np.zeros(1)

array([0.])

In [14]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
arr = np.zeros((3, 4))
arr.ndim

2

In [16]:
arr = np.zeros((1, 3, 4))
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [17]:
arr.ndim

3

In [18]:
arr = np.zeros((1, 1, 3, 4))
arr

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [19]:
arr.ndim

4

In [20]:
arr = np.zeros((1, 1, 1, 3, 4))
arr

array([[[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]]])

In [21]:
arr.ndim

5

In [22]:
arr

array([[[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]]])

In [23]:
arr = np.ones((3, 4))

In [24]:
arr.ndim

2

In [25]:
arr.shape

(3, 4)

In [26]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
arr + 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [28]:
a = arr * 5

In [29]:
a

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [30]:
a - 1

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [31]:
np.eye(3) #Return a 2-D array with ones on the diagonal and zeros elsewhere.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.eye(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [33]:
np.empty((3, 4)) #Return a new array of given shape and type, without initializing entries

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [34]:
#optional >> random module

import random
random.choice((1, 2, 3, 4, 5))

2

In [35]:
random.choice('Ajay')

'a'

In [36]:
random.randrange(1, 10)

7

In [37]:
random.random() # a random no is generated between 0(included) and 1 (excluded)

0.017769477320319083

In [38]:
lis = [1, 2, 3, 4, 5]
lis

[1, 2, 3, 4, 5]

In [40]:
random.shuffle(lis)

In [41]:
lis

[2, 3, 1, 4, 5]

In [42]:
random.uniform(7, 14)

12.573243031183921

In [43]:

#random numbers related concepts in numpy
np.array([])

array([], dtype=float64)

In [44]:
np.random.random_sample()

0.4880220291522446

In [45]:
np.random.random_sample((5, ))

array([0.03546162, 0.96439444, 0.86559857, 0.45990473, 0.68239288])

In [46]:
np.random.rand(1)

array([0.89826893])

In [48]:
np.random.rand(2, 3)

array([[0.19956744, 0.85663567, 0.76798966],
       [0.01678481, 0.29287439, 0.5507118 ]])

In [49]:
np.random.randn(2,3)

array([[-0.85502332, -0.06881989,  0.76879661],
       [ 0.64187717,  1.46547139, -1.07173591]])

In [51]:
arr = np.random.randint(1, 5, size= (3, 4))

In [52]:
arr.ndim

2

In [53]:
arr.shape

(3, 4)

In [54]:
arr.size

12

In [55]:
arr

array([[1, 3, 3, 4],
       [4, 3, 3, 3],
       [4, 4, 1, 4]])

In [58]:
#reshaping the array

arr1 = arr.reshape(2, 6)

In [59]:
arr1.shape

(2, 6)

In [60]:
arr1.size

12

In [61]:
arr

array([[1, 3, 3, 4],
       [4, 3, 3, 3],
       [4, 4, 1, 4]])

In [62]:
arr.size

12

In [63]:
#array size will not change, always resape parameter should be multiplication of original array size

In [64]:
arr

array([[1, 3, 3, 4],
       [4, 3, 3, 3],
       [4, 4, 1, 4]])

In [65]:
arr.size

12

In [69]:
arr.reshape(12,1)

array([[1],
       [3],
       [3],
       [4],
       [4],
       [3],
       [3],
       [3],
       [4],
       [4],
       [1],
       [4]])

In [70]:
arr.reshape(1, 12)

array([[1, 3, 3, 4, 4, 3, 3, 3, 4, 4, 1, 4]])

In [72]:
arr.reshape(3, 3)

ValueError: cannot reshape array of size 12 into shape (3,3)

In [73]:
arr.reshape(3,4)

array([[1, 3, 3, 4],
       [4, 3, 3, 3],
       [4, 4, 1, 4]])

In [74]:
#case when you dont know in reshape what should be the column count

arr.reshape(4, -1)

array([[1, 3, 3],
       [4, 4, 3],
       [3, 3, 4],
       [4, 1, 4]])

In [75]:
arr.reshape(2, -1)

array([[1, 3, 3, 4, 4, 3],
       [3, 3, 4, 4, 1, 4]])

In [76]:
arr.reshape(2, -100)

array([[1, 3, 3, 4, 4, 3],
       [3, 3, 4, 4, 1, 4]])

In [78]:
arr1 = arr.reshape(-1, 3)#you know column count but no row count

In [79]:
arr1.size

12

In [81]:
arr.reshape(12, 1)

array([[1],
       [3],
       [3],
       [4],
       [4],
       [3],
       [3],
       [3],
       [4],
       [4],
       [1],
       [4]])

In [82]:
arr.reshape(12, 1).base #to see the original array

array([[1, 3, 3, 4],
       [4, 3, 3, 3],
       [4, 4, 1, 4]])

In [85]:
arr.reshape(2, 2, 3)

array([[[1, 3, 3],
        [4, 4, 3]],

       [[3, 3, 4],
        [4, 1, 4]]])

In [86]:
arr.reshape(1, 2, 2, 3)

array([[[[1, 3, 3],
         [4, 4, 3]],

        [[3, 3, 4],
         [4, 1, 4]]]])

In [87]:
arr.reshape(1, 2, 2, 3).ndim

4

In [88]:
arr.reshape(4, 3, 1) #3 rows 1 column repeated 4 times in the third dimension

array([[[1],
        [3],
        [3]],

       [[4],
        [4],
        [3]],

       [[3],
        [3],
        [4]],

       [[4],
        [1],
        [4]]])

In [89]:
#conditions on array

arr1 = np.random.randint(1, 10, (5,6))

In [90]:
arr1

array([[3, 8, 8, 1, 1, 7],
       [4, 4, 5, 5, 2, 5],
       [2, 2, 9, 9, 2, 4],
       [8, 5, 4, 1, 4, 9],
       [7, 8, 4, 9, 6, 9]])

In [91]:
arr1.shape

(5, 6)

In [92]:
arr1.ndim

2

In [93]:
arr1.size

30

In [94]:
arr1 > 3

array([[False,  True,  True, False, False,  True],
       [ True,  True,  True,  True, False,  True],
       [False, False,  True,  True, False,  True],
       [ True,  True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [95]:
arr1[arr1> 3]

array([8, 8, 7, 4, 4, 5, 5, 5, 9, 9, 4, 8, 5, 4, 4, 9, 7, 8, 4, 9, 6, 9])

In [96]:
arr1[arr1 < 3]

array([1, 1, 2, 2, 2, 2, 1])

In [97]:
arr1

array([[3, 8, 8, 1, 1, 7],
       [4, 4, 5, 5, 2, 5],
       [2, 2, 9, 9, 2, 4],
       [8, 5, 4, 1, 4, 9],
       [7, 8, 4, 9, 6, 9]])

In [98]:
#To access elements in the array
arr1[0]

array([3, 8, 8, 1, 1, 7])

In [99]:
arr1[1]

array([4, 4, 5, 5, 2, 5])

In [100]:
arr1[1][0]

4

In [101]:
arr1

array([[3, 8, 8, 1, 1, 7],
       [4, 4, 5, 5, 2, 5],
       [2, 2, 9, 9, 2, 4],
       [8, 5, 4, 1, 4, 9],
       [7, 8, 4, 9, 6, 9]])

In [103]:
arr1[0:3] #oth row, 1st row and 2nd row

array([[3, 8, 8, 1, 1, 7],
       [4, 4, 5, 5, 2, 5],
       [2, 2, 9, 9, 2, 4]])

In [106]:
arr1[0:3, [0, 2]] #0to2nd row and 0th and 2nd column

array([[3, 8],
       [4, 5],
       [2, 9]])

In [107]:
#slicing on both rows and column

In [110]:
arr1

array([[3, 8, 8, 1, 1, 7],
       [4, 4, 5, 5, 2, 5],
       [2, 2, 9, 9, 2, 4],
       [8, 5, 4, 1, 4, 9],
       [7, 8, 4, 9, 6, 9]])

In [109]:
arr1[0:3, 1:3]

array([[8, 8],
       [4, 5],
       [2, 9]])

In [111]:
arr1[0:2, [0,1]]

array([[3, 8],
       [4, 4]])

In [112]:
arr1[0, [1, 3]]

array([8, 1])

In [113]:
arr1[2:4, [0, 3]]

array([[2, 9],
       [8, 1]])

In [114]:
arr1[2:5]

array([[2, 2, 9, 9, 2, 4],
       [8, 5, 4, 1, 4, 9],
       [7, 8, 4, 9, 6, 9]])

In [115]:
arr1[2:5, 0:2]

array([[2, 2],
       [8, 5],
       [7, 8]])

In [116]:
#mathematical operation on two arrays
arr1 = np.random.randint(1, 3, (3, 3))
arr2 = np.random.randint(1, 3, (3, 3))

In [117]:
arr1

array([[1, 2, 1],
       [2, 1, 1],
       [2, 1, 1]])

In [118]:
arr2

array([[2, 1, 1],
       [1, 2, 1],
       [1, 1, 2]])

In [119]:
arr1+arr2 #indewise elment addition

array([[3, 3, 2],
       [3, 3, 2],
       [3, 2, 3]])

In [120]:
arr1-arr2 #indexwise element substraction

array([[-1,  1,  0],
       [ 1, -1,  0],
       [ 1,  0, -1]])

In [121]:
arr1 * arr2 #index wise multiplication

array([[2, 2, 1],
       [2, 2, 1],
       [2, 1, 2]])

In [122]:
arr1, arr2

(array([[1, 2, 1],
        [2, 1, 1],
        [2, 1, 1]]),
 array([[2, 1, 1],
        [1, 2, 1],
        [1, 1, 2]]))

In [123]:
arr1 / arr2 #index wise divison

array([[0.5, 2. , 1. ],
       [2. , 0.5, 1. ],
       [2. , 1. , 0.5]])

In [127]:
4/0

ZeroDivisionError: division by zero

In [126]:
arr1 / 0 #in python zero divion error will come, but in numpy no error

/tmp/ipykernel_3900/824215542.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1 / 0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [124]:
#matric multiplication>> different from index wise multiplication

arr1 @ arr2 #1st way to do matrix multiplication

array([[5, 6, 5],
       [6, 5, 5],
       [6, 5, 5]])

In [125]:
np.dot(arr1, arr2) #ndst way to do matrix multiplication

array([[5, 6, 5],
       [6, 5, 5],
       [6, 5, 5]])

In [128]:
arr = np.zeros((3, 4))

In [129]:
#broadcasting
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [130]:
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [131]:
arr-5

array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])

In [132]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [133]:
a = np.array([1, 2, 3, 4])

In [134]:
a

array([1, 2, 3, 4])

In [135]:
a.ndim

1

In [136]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [141]:
a = np.array([[1, 2, 3, 4]])

In [142]:
a

array([[1, 2, 3, 4]])

In [143]:
#Transpose
a.T

array([[1],
       [2],
       [3],
       [4]])

In [145]:
arr1

array([[1, 2, 1],
       [2, 1, 1],
       [2, 1, 1]])

In [146]:
arr1.T

array([[1, 2, 2],
       [2, 1, 1],
       [1, 1, 1]])