In [1]:
import numpy as np

In [2]:
arr1 = np.random.randint(1, 3, (3,3))
arr2 = np.random.randint(1, 3, (3,3))

In [3]:
arr1

array([[2, 1, 2],
       [1, 2, 2],
       [1, 1, 2]])

In [4]:
arr1.flatten() #Return a copy of the array collapsed into one dimension.

array([2, 1, 2, 1, 2, 2, 1, 1, 2])

In [5]:
#expand dimesnion
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [6]:
arr.ndim

1

In [13]:
np.expand_dims(arr, axis = 0) #increases the dimension by 1 at provoided axis

array([[1, 2, 3, 4]])

In [10]:
np.expand_dims(arr, axis = 1)

array([[1],
       [2],
       [3],
       [4]])

In [12]:
np.expand_dims(arr, axis = 1).ndim

2

In [11]:
arr

array([1, 2, 3, 4])

In [14]:
arr = np.zeros((3, 4))

In [15]:
arr.ndim

2

In [16]:
np.expand_dims(arr, axis=0)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [17]:
np.expand_dims(arr, axis=1)

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [18]:
np.expand_dims(arr, axis=0).ndim

3

In [19]:
a = np.array([[1], [2], [3]])

In [20]:
a

array([[1],
       [2],
       [3]])

In [21]:
a.ndim

2

In [22]:
np.squeeze(a) #Remove axes of length one from `a`

array([1, 2, 3])

In [23]:
a

array([[1],
       [2],
       [3]])

In [25]:
np.repeat(a, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [26]:
arr1

array([[2, 1, 2],
       [1, 2, 2],
       [1, 1, 2]])

In [27]:
np.repeat(arr1, 2)

array([2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2])

In [28]:
np.repeat(arr1, 2, axis=0)

array([[2, 1, 2],
       [2, 1, 2],
       [1, 2, 2],
       [1, 2, 2],
       [1, 1, 2],
       [1, 1, 2]])

In [29]:
np.repeat(arr1, 3, axis=0)

array([[2, 1, 2],
       [2, 1, 2],
       [2, 1, 2],
       [1, 2, 2],
       [1, 2, 2],
       [1, 2, 2],
       [1, 1, 2],
       [1, 1, 2],
       [1, 1, 2]])

In [30]:
np.repeat(arr1, 3, axis=1)

array([[2, 2, 2, 1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2, 2, 2, 2],
       [1, 1, 1, 1, 1, 1, 2, 2, 2]])

In [31]:
a

array([[1],
       [2],
       [3]])

In [33]:
np.roll(a, -1)

array([[2],
       [3],
       [1]])

In [34]:
np.roll(a, -2)

array([[3],
       [1],
       [2]])

In [37]:
c = np.array([[1,2], [3, 4], [5,6], [7,8]])

In [38]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [40]:
np.roll(c, 2)

array([[7, 8],
       [1, 2],
       [3, 4],
       [5, 6]])

In [41]:
np.roll(c, 2, axis=0)

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [42]:
arr1

array([[2, 1, 2],
       [1, 2, 2],
       [1, 1, 2]])

In [43]:
arr2

array([[1, 2, 2],
       [2, 1, 2],
       [1, 1, 2]])

In [44]:
arr1 + arr2

array([[3, 3, 4],
       [3, 3, 4],
       [2, 2, 4]])

In [45]:
arr1-arr2

array([[ 1, -1,  0],
       [-1,  1,  0],
       [ 0,  0,  0]])

In [46]:
arr1 * arr2

array([[2, 2, 4],
       [2, 2, 4],
       [1, 1, 4]])

In [47]:
arr1 > arr2

array([[ True, False, False],
       [False,  True, False],
       [False, False, False]])

In [48]:
arr1

array([[2, 1, 2],
       [1, 2, 2],
       [1, 1, 2]])

In [49]:
~arr1

array([[-3, -2, -3],
       [-2, -3, -3],
       [-2, -2, -3]])

In [50]:
#operations on numpy string array

In [51]:
d = np.array(["pw", "skills"])

In [52]:
d

array(['pw', 'skills'], dtype='<U6')

In [53]:
np.char.upper(d)

array(['PW', 'SKILLS'], dtype='<U6')

In [54]:
np.char.capitalize(d)

array(['Pw', 'Skills'], dtype='<U6')

In [55]:
#mathematical functions

In [56]:
arr1

array([[2, 1, 2],
       [1, 2, 2],
       [1, 1, 2]])

In [57]:
np.sin(arr1)

array([[0.90929743, 0.84147098, 0.90929743],
       [0.84147098, 0.90929743, 0.90929743],
       [0.84147098, 0.84147098, 0.90929743]])

In [58]:
np.cos(arr1)

array([[-0.41614684,  0.54030231, -0.41614684],
       [ 0.54030231, -0.41614684, -0.41614684],
       [ 0.54030231,  0.54030231, -0.41614684]])

In [59]:
np.tan(arr1)

array([[-2.18503986,  1.55740772, -2.18503986],
       [ 1.55740772, -2.18503986, -2.18503986],
       [ 1.55740772,  1.55740772, -2.18503986]])

In [60]:
np.log10(arr1)

array([[0.30103, 0.     , 0.30103],
       [0.     , 0.30103, 0.30103],
       [0.     , 0.     , 0.30103]])

In [61]:
np.exp(arr1)

array([[7.3890561 , 2.71828183, 7.3890561 ],
       [2.71828183, 7.3890561 , 7.3890561 ],
       [2.71828183, 2.71828183, 7.3890561 ]])

In [62]:
np.power(arr1, 3)

array([[8, 1, 8],
       [1, 8, 8],
       [1, 1, 8]])

In [63]:
np.mean(arr1)

1.5555555555555556

In [64]:
np.max(arr1)

2

In [65]:
np.min(arr1)

1

In [66]:
np.std(arr1)

0.4969039949999533

In [67]:
np.var(arr1)

0.2469135802469136

In [68]:
arr1-arr2

array([[ 1, -1,  0],
       [-1,  1,  0],
       [ 0,  0,  0]])

In [70]:
np.subtract(arr1, arr2)

array([[ 1, -1,  0],
       [-1,  1,  0],
       [ 0,  0,  0]])

In [71]:
arr1 *arr2

array([[2, 2, 4],
       [2, 2, 4],
       [1, 1, 4]])

In [72]:
np.multiply(arr1, arr2)

array([[2, 2, 4],
       [2, 2, 4],
       [1, 1, 4]])

In [73]:
np.mod(arr1, arr2) #return elment wise remainder

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 0]])

In [74]:
np.sqrt(arr1)

array([[1.41421356, 1.        , 1.41421356],
       [1.        , 1.41421356, 1.41421356],
       [1.        , 1.        , 1.41421356]])

In [75]:
#sort search

e = np.array([5, 6, 1, 2])

In [76]:
e

array([5, 6, 1, 2])

In [77]:
np.sort(e)

array([1, 2, 5, 6])

In [78]:
f = np.array([5, 199, 200, 6, 7, 8])

In [79]:
f

array([  5, 199, 200,   6,   7,   8])

In [80]:
np.sort(f)

array([  5,   6,   7,   8, 199, 200])

In [81]:
np.searchsorted(f, 170) #Find indices where elements should be inserted to maintain order.

6

In [83]:
f = np.array([5, 199, 200, 6, 7, 0, 0, 0, 8])

In [84]:
f

array([  5, 199, 200,   6,   7,   0,   0,   0,   8])

In [85]:
np.count_nonzero(f)

6

In [88]:
f[f > 0]

array([  5, 199, 200,   6,   7,   8])

In [90]:
np.where(f>0)

(array([0, 1, 2, 3, 4, 8]),)

In [91]:
np.extract(f>0, f)

array([  5, 199, 200,   6,   7,   8])

In [92]:
f

array([  5, 199, 200,   6,   7,   0,   0,   0,   8])

In [93]:
f.byteswap()

array([  360287970189639680, -4107282860161892352, -4035225266123964416,
         432345564227567616,   504403158265495552,                    0,
                          0,                    0,   576460752303423488])

In [94]:
#matrix>> 2d array

import numpy.matlib as nm

In [95]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [97]:
nm.ones((3, 4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [102]:
#numpy linear algebra

arr1 = np.random.randint(1, 10, (3, 3))
arr2 = np.random.randint(1, 10, (3, 3))

In [103]:
arr1

array([[4, 5, 3],
       [6, 7, 4],
       [6, 5, 8]])

In [104]:
arr2

array([[8, 1, 9],
       [6, 5, 4],
       [9, 7, 6]])

In [105]:
arr1 @ arr2

array([[ 89,  50,  74],
       [126,  69, 106],
       [150,  87, 122]])

In [106]:
arr1

array([[4, 5, 3],
       [6, 7, 4],
       [6, 5, 8]])

In [107]:
np.linalg.det(arr1)

-12.000000000000016

In [108]:
np.linalg.inv(arr1)

array([[-3.        ,  2.08333333,  0.08333333],
       [ 2.        , -1.16666667, -0.16666667],
       [ 1.        , -0.83333333,  0.16666667]])

In [109]:
a = np.array([[7, 5.3, -3], [3, -5, 2], [5, 3, -7]])

In [110]:
a

array([[ 7. ,  5.3, -3. ],
       [ 3. , -5. ,  2. ],
       [ 5. ,  3. , -7. ]])

In [111]:
b = np.array([16, 8, 0])

In [112]:
b

array([16,  8,  0])

In [113]:
np.linalg.solve(a, b)

array([2.59630607, 0.84432718, 2.21635884])