In [1]:
#library>> collection of modules and package
#numpy >> numerical python
#2005 by travis oliphant

In [2]:
import numpy as np

In [3]:
np.__version__

'1.24.3'

In [4]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [6]:
lis = [1, 2, 3, 4, 3+5j, "Ajay", "Bijay"]
type(lis)

list

In [ ]:
#numpy stores the data in an array
#An array is a container used to to store the data of same type

In [7]:
#why numpy
#due to array>>>computation becomes fast, continuous memory allocation

In [8]:
l = [1, 2, 3, 4]

In [9]:
arr = np.array(l)

In [10]:
arr

array([1, 2, 3, 4])

In [11]:
type(arr)

numpy.ndarray

In [12]:
arr.ndim

1

In [13]:
l = [1, 2, 3, 4, "Saurabh"]
np.array(l)

array(['1', '2', '3', '4', 'Saurabh'], dtype='<U11')

In [15]:
arr1  =np.array([[1, 2, 3], [4, 5, 6]])

In [16]:
arr1.ndim

2

In [23]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
arr1.shape

(2, 3)

In [19]:
mat = np.matrix([1, 2, 3, 4])

In [21]:
mat

matrix([[1, 2, 3, 4]])

In [22]:
type(mat)

numpy.matrix

In [25]:
arr2 = np.array([[[1,2], [3, 4]]])

In [27]:
arr2.ndim

3

In [28]:
arr2 = np.array([[[[1,2], [3, 4]]]])

In [29]:
arr2

array([[[[1, 2],
         [3, 4]]]])

In [30]:
arr2.ndim

4

In [31]:
arr2 = np.array([[[[[1,2], [3, 4]]]]])
arr2.ndim

5

In [32]:
l = [1, 2, 3]
np.asarray(l)

array([1, 2, 3])

In [34]:
np.asarray(mat)

array([[1, 2, 3, 4]])

In [35]:
np.asanyarray([1, 2,3])

array([1, 2, 3])

In [36]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4]])

In [37]:
t = ([1, 2, 3], [4, 5, 6])

In [39]:
arr = np.array(t)

In [40]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
l = [1, 2, 3, 4]
arr = np.array(l)

In [43]:
arr

array([1, 2, 3, 4])

In [44]:
arr[0]

1

In [45]:
arr[0] = 100

In [46]:
arr

array([100,   2,   3,   4])

In [47]:
#is array mutable>> yes array is mutable

In [ ]:
#what is difference between deep and shallow copy?

In [48]:
arr = np.array([1, 2, 3, 4])

In [49]:
arr

array([1, 2, 3, 4])

In [50]:
a = arr #shallow copy

In [51]:
a

array([1, 2, 3, 4])

In [52]:
arr

array([1, 2, 3, 4])

In [54]:
a[0] = 500

In [55]:
a

array([500,   2,   3,   4])

In [56]:
arr

array([500,   2,   3,   4])

In [57]:
arr = np.array([1, 2, 3, 4])
a = arr.copy()#deep copy


In [58]:
a

array([1, 2, 3, 4])

In [59]:
arr

array([1, 2, 3, 4])

In [60]:
a[0] = 500

In [61]:
a

array([500,   2,   3,   4])

In [62]:
arr

array([1, 2, 3, 4])

In [63]:
#multiple ways to generate array

np.fromfunction(lambda i, j: i == j, (3, 3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
#for 1 d array using from func
np.fromfunction(lambda i: i**2, (5,), dtype=float)

In [64]:
np.fromfunction(lambda i, j: i*j, (3, 3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [65]:
for i in range(5):
    print(i)

0
1
2
3
4


In [71]:
iterable = (i for i in range(5))

In [72]:
iterable

<generator object <genexpr> at 0x00000168638EA5A0>

In [73]:
np.fromiter(iterable, int)

array([0, 1, 2, 3, 4])

In [74]:
np.fromstring('22 23 24', sep = " " )

array([22., 23., 24.])

In [75]:
np.fromstring('22,23,24', sep = "," )

array([22., 23., 24.])

In [77]:
string = "Ajay, Bijay, Sanjay"
np.array(string.split(","))

array(['Ajay', ' Bijay', ' Sanjay'], dtype='<U7')

In [79]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [84]:
iter(range(10))

In [83]:
np.arange(1, 10, 0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [94]:
a = np.zeros([5])

In [95]:
a

array([0., 0., 0., 0., 0.])

In [96]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [97]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [99]:
np.ones((3, 4), dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [100]:
np.twos((3, 4))

AttributeError: module 'numpy' has no attribute 'twos'

In [101]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [102]:
np.zeros((1, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [104]:
np.zeros((3, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [109]:
arr = np.zeros((1, 2, 2, 3, 4))

In [110]:
arr.shape

(1, 2, 2, 3, 4)

In [112]:
arr.ndim

5

In [113]:
arr = np.ones((3, 4))

In [114]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [115]:
arr + 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [116]:
arr *5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [117]:
arr -3

array([[-2., -2., -2., -2.],
       [-2., -2., -2., -2.],
       [-2., -2., -2., -2.]])

In [118]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [120]:
np.random.random_sample()

0.4727833384297476

In [121]:
np.random.random_sample((5, ))

array([0.05545415, 0.0427602 , 0.70142388, 0.76885922, 0.54010064])

In [122]:
np.random.rand(1)

array([0.35332669])

In [124]:
np.random.rand(2, 3)

array([[0.3594015 , 0.83649108, 0.525128  ],
       [0.7204877 , 0.88586571, 0.88366743]])

In [125]:
np.random.randn(2, 3)

array([[-0.22669917, -0.25574292,  2.15191615],
       [ 0.19684163,  0.07092812, -1.37810566]])

In [127]:
arr = np.random.randint(1, 5, size = (3, 4))

In [128]:
arr

array([[3, 2, 2, 2],
       [2, 2, 3, 4],
       [3, 4, 3, 4]])

In [129]:
arr.ndim

2

In [130]:
arr.shape

(3, 4)

In [131]:
arr

array([[3, 2, 2, 2],
       [2, 2, 3, 4],
       [3, 4, 3, 4]])

In [132]:
arr.size

12

In [133]:
#reshaping

arr.reshape(2, 6)

array([[3, 2, 2, 2, 2, 2],
       [3, 4, 3, 4, 3, 4]])

In [136]:
arr.reshape(1, 12)

array([[3, 2, 2, 2, 2, 2, 3, 4, 3, 4, 3, 4]])

In [137]:
arr.reshape(4, -100)

array([[3, 2, 2],
       [2, 2, 2],
       [3, 4, 3],
       [4, 3, 4]])

In [138]:
arr.reshape(-1, 2)

array([[3, 2],
       [2, 2],
       [2, 2],
       [3, 4],
       [3, 4],
       [3, 4]])

In [139]:
arr.reshape(-1, 2).base

array([[3, 2, 2, 2],
       [2, 2, 3, 4],
       [3, 4, 3, 4]])

In [140]:
arr.reshape(2,2,3)

array([[[3, 2, 2],
        [2, 2, 2]],

       [[3, 4, 3],
        [4, 3, 4]]])

In [144]:
arr.reshape(1,2,2,3).size

12

In [146]:
arr1 = np.random.randint(1, 10, (5, 6))

In [147]:
arr1.shape

(5, 6)

In [148]:
arr1.ndim

2

In [149]:
arr1.size

30

In [153]:
arr1[arr1 < 3]

array([1, 2, 1, 1, 2])

In [154]:
arr1

array([[4, 3, 1, 7, 3, 8],
       [9, 4, 5, 2, 5, 6],
       [7, 7, 1, 3, 7, 6],
       [9, 7, 7, 5, 3, 3],
       [1, 5, 4, 2, 3, 5]])

In [156]:
arr1[0:3]

array([[4, 3, 1, 7, 3, 8],
       [9, 4, 5, 2, 5, 6],
       [7, 7, 1, 3, 7, 6]])

In [157]:
arr1[0:3, [0,2]]

array([[4, 1],
       [9, 5],
       [7, 1]])

In [160]:
arr1[2:5, 0:2]

array([[7, 7],
       [9, 7],
       [1, 5]])

In [161]:
arr1 = np.random.randint(1, 2, (3,3))
arr2 = np.random.randint(1, 2, (3,3))

In [162]:
arr1+arr2

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [163]:
arr1-arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [169]:
arr1, arr2

(array([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]),
 array([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]))

In [164]:
arr1 * arr2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [165]:
arr1/arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [166]:
4/0

ZeroDivisionError: division by zero

In [168]:
arr1/0

C:\Users\ajayk\AppData\Local\Temp\ipykernel_19920\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [170]:
#matrix multiplication

arr1 @ arr2

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [171]:
np.dot(arr1, arr2)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [172]:
#broadcasting

In [175]:
arr = np.zeros((3, 4))

In [176]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [177]:
arr+1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [178]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [179]:
arr-5

array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])

In [180]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [181]:
arr1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [185]:
arr1 = np.random.randint(1, 6, (3,3))


In [186]:
arr1

array([[5, 4, 5],
       [1, 4, 5],
       [4, 1, 3]])

In [187]:
arr1.T

array([[5, 1, 4],
       [4, 4, 1],
       [5, 5, 3]])

In [190]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [191]:
arr1 = np.random.randint(1, 6, (3,3))
arr2 = np.random.randint(1, 6, (3,3))

In [196]:
arr1

array([[4, 5, 5],
       [4, 3, 4],
       [3, 5, 4]])

In [193]:
arr1.flatten()

array([4, 5, 5, 4, 3, 4, 3, 5, 4])

In [194]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [195]:
arr.ndim

1

In [197]:
arr

array([1, 2, 3, 4])

In [198]:
np.expand_dims(arr, axis = 0)

array([[1, 2, 3, 4]])

In [200]:
a = np.expand_dims(arr, axis = 1)

In [201]:
a

array([[1],
       [2],
       [3],
       [4]])

In [202]:
np.squeeze(a)

array([1, 2, 3, 4])

In [203]:
a

array([[1],
       [2],
       [3],
       [4]])

In [204]:
np.repeat(a, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])

In [205]:
d = np.array(["pw", "skills"])

In [206]:
d

array(['pw', 'skills'], dtype='<U6')

In [207]:
np.char.upper(d)

array(['PW', 'SKILLS'], dtype='<U6')

In [208]:
np.char.capitalize(d)

array(['Pw', 'Skills'], dtype='<U6')

In [209]:
arr1

array([[4, 5, 5],
       [4, 3, 4],
       [3, 5, 4]])

In [210]:
np.sin(arr1)

array([[-0.7568025 , -0.95892427, -0.95892427],
       [-0.7568025 ,  0.14112001, -0.7568025 ],
       [ 0.14112001, -0.95892427, -0.7568025 ]])

In [211]:
np.cos(arr1)

array([[-0.65364362,  0.28366219,  0.28366219],
       [-0.65364362, -0.9899925 , -0.65364362],
       [-0.9899925 ,  0.28366219, -0.65364362]])

In [212]:
np.tan(arr1)

array([[ 1.15782128, -3.38051501, -3.38051501],
       [ 1.15782128, -0.14254654,  1.15782128],
       [-0.14254654, -3.38051501,  1.15782128]])

In [213]:
np.log10(arr1)

array([[0.60205999, 0.69897   , 0.69897   ],
       [0.60205999, 0.47712125, 0.60205999],
       [0.47712125, 0.69897   , 0.60205999]])

In [214]:
np.exp(arr1)

array([[ 54.59815003, 148.4131591 , 148.4131591 ],
       [ 54.59815003,  20.08553692,  54.59815003],
       [ 20.08553692, 148.4131591 ,  54.59815003]])

In [215]:
np.power(arr1, 3)

array([[ 64, 125, 125],
       [ 64,  27,  64],
       [ 27, 125,  64]], dtype=int32)

In [216]:
np.mean(arr1)

4.111111111111111

In [217]:
np.max(arr1)

5

In [218]:
np.min(arr1)

3

In [219]:
import numpy.matlib as nm

In [220]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [221]:
nm.ones((3, 4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [224]:
arr1.T

array([[4, 4, 3],
       [5, 3, 5],
       [5, 4, 4]])

In [225]:
arr1

array([[4, 5, 5],
       [4, 3, 4],
       [3, 5, 4]])

In [226]:
np.linalg.det(arr1)

2.9999999999999996

In [227]:
np.linalg.inv(arr1)

array([[-2.66666667,  1.66666667,  1.66666667],
       [-1.33333333,  0.33333333,  1.33333333],
       [ 3.66666667, -1.66666667, -2.66666667]])

In [229]:
a = np.array([[7, 5.3, -3], [3, -5, 2], [5, 3, -7]])

In [230]:
a

array([[ 7. ,  5.3, -3. ],
       [ 3. , -5. ,  2. ],
       [ 5. ,  3. , -7. ]])

In [231]:
b = np.array([16, 8, 0])

In [232]:
b

array([16,  8,  0])

In [233]:
np.linalg.solve(a, b)

array([2.59630607, 0.84432718, 2.21635884])

In [234]:
round(2.33555, 2)

2.34

array([ 0.,  1.,  4.,  9., 16.])

In [240]:
np.all([[True,True],[True,True]])

True